@hostname = http://localhost:3001

/// .......................STUDENTS ATTENDANCE API ......................///
###
post {{hostname}}/student_attendance
Content-Type: application/json

{
    "attendanceDate":"31-01-2022",
    "status":"p",
    "studentRecordId":"63d4026d817e833cbd0c6ac8",
    "termId":"63d966edcbdcf350e3fdefd4"
}


###
put {{hostname}}/student_attendance/63d9122ac759e654d1284765
Content-Type: application/json

{
    "status":"a"
}

###
get {{hostname}}/student_attendance/

###
delete {{hostname}}/student_attendance/63d90b0422d7b1250ad1dd65

###

