@hostname = http://localhost:3001

/// ..............class School api .................///
###
post {{hostname}}/class_school
Content-Type: application/json

{
    "classId":"63d91c365744496640675615",
    "schoolId":"63d95aa8cbdcf350e3fdef12"
}

###
get {{hostname}}/class_school


###
get {{hostname}}/class_school/classes/63d931b719dfd07c302c6d45


###
get {{hostname}}/class_school/class/63d931b719dfd07c302c6d43


###
get {{hostname}}/class_school/school/class/63d931b719dfd07c302c6d43


###
DELETE {{hostname}}/class_school/63d91cd4d777a814651036c0

###
get {{hostname}}/class_school/count/63d95aa8cbdcf350e3fdef12



###

/// .......................HOMEWORK API ......................///
get {{hostname}}/homework

###
put {{hostname}}/homework


###
