

// .......................HOMEWORK SECTION API ......................///
post {{hostname}}/homework_section
Content-Type: application/json

{
    "title":"homework 1",
    "description":"submit your homework",
    "setBy":"63d4026d817e833cbd0c6ac8",
    "sessionId":"63d4026d817e833cbd0c6ac8",
    "schoolId":"63d4026d817e833cbd0c6ac8",
    "subjectId":"63d4026d817e833cbd0c6ac8",
    "sectionId":"63d4026d817e833cbd0c6ac8"
}
###
put {{hostname}}/homework_section
@hostname = http://localhost:3001

###

###
/// homework section router ////
get {{hostname}}/homework_section
###
post {{hostname}}/homework_section
Content-Type: application/json

{
    "title":"My Homework",
    "description":"Submit by tomorrow",
    "session:":"631142782638c3a53911a201",
    "school:":"63111b101aa048a013171e25",
    "section":"63111b101aa048a013171e25"
}
###
delete {{hostname}}/homework_section/63d409f9d6f3ea07f0471148
###
put  {{hostname}}/homework_section/631143712638c3a53911a20d
Content-Type: application/json

{
    "section":"63111b101aa048a013171e25"
}

#######

// get home work section for the term

get {{hostname}}/homework_section/63d966edcbdcf350e3fdefd4

