/// .......................SUBJECT ATTENDANCE API ......................///
@hostname = http://localhost:3001

###
post {{hostname}}/subject
Content-Type: application/json

{
    "label":"English language",
    "code":"eng",
    "type":"theory",
    "classSchoolId":"63d4026d817e833cbd0c6ac8"
}


###
put {{hostname}}/subject/63d9203df7998ab93630a906
Content-Type: application/json

{
    "label":"Mathematics",
    "code":"Math101",
    "type":"theory"

}

###
get {{hostname}}/subject

// find all the subjects assigned to this class school id
###
get {{hostname}}/subject/class/63d9db1adc2cae33cf245b17

###
delete {{hostname}}/subject/63d9203df7998ab93630a906
