@hostname = http://localhost:3001

###
get {{hostname}}/timetable

###


###
get {{hostname}}/timetable/group/63d966edcbdcf350e3fdefd4

###
post {{hostname}}   
Content-Type: application/json

{
    "startTime":""
}


####
post {{hostname}}/timetable/class
Content-type:application/json

{
    "termId":"63d966edcbdcf350e3fdefd4",
    "sectionId":"63d9dbb6b1255479e13c0aff"
}
